name: 'Deploy to AWS S3'
description: 'Deploy website via AWS S3.'
inputs:
  bucket:
    description: 'The S3 bucket name.'
    required: true
  bucket-region:
    description: 'The region of the bucket.'
    required: true
  dist-folder:
    description: 'The folder containing the files.'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed website.'
runs:
  using: 'node20'
  main: 'main.js'